# Generated by Django 4.0.5 on 2022-07-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About me'},
        ),
        migrations.AlterModelOptions(
            name='backgroundimages',
            options={'verbose_name_plural': 'Background Images'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name_plural': 'Songs'},
        ),
        migrations.AddField(
            model_name='songs',
            name='audio',
            field=models.FileField(default=1, upload_to='audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='cover_image',
            field=models.ImageField(default='/defaultbook.jpg', upload_to='cover_images'),
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=20, null=True)),
                ('subtitles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(default='/defaultbook.jpg', upload_to='cover_images')),
                ('background_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.backgroundimages')),
            ],
        ),
    ]
