# Generated by Django 4.0.5 on 2022-07-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_backgroundimage_background_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
